# Generated by Django 4.1.7 on 2025-01-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Universe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("launch_file_path", models.CharField(max_length=200)),
                (
                    "ros_version",
                    models.CharField(
                        choices=[("ROS1", "ROS1"), ("ROS2", "ROS2")],
                        default="none",
                        max_length=4,
                    ),
                ),
                (
                    "visualization",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("console", "Console"),
                            ("gazebo_gra", "Gazebo GRA"),
                            ("gazebo_rae", "Gazebo RAE"),
                            ("gzsim_gra", "Gz Sim GRA"),
                            ("gzsim_rae", "Gz Sim RAE"),
                            ("physic_gra", "Physic GRA"),
                            ("physic_rae", "Physic RAE"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "world",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("gazebo", "Gazebo"),
                            ("drones", "Gazebo Drones"),
                            ("gzsimdrones", "Gz Sim Drones"),
                            ("physical", "Physical"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": '"universes"',
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_id", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(max_length=400)),
                ("tags", models.CharField(default='{"tags": ""}', max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("PROTOTYPE", "PROTOTYPE"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("template", models.CharField(blank=True, default="", max_length=200)),
                (
                    "worlds",
                    models.ManyToManyField(
                        db_table='"exercises_universes"',
                        default=None,
                        to="exercises.universe",
                    ),
                ),
            ],
            options={
                "db_table": '"exercises"',
            },
        ),
    ]
