# Generated by Django 4.1.7 on 2024-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0026_exercise_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="worlds",
            field=models.ManyToManyField(
                db_table='"exercises_universes"', default=None, to="exercises.world"
            ),
        ),
        migrations.AlterModelTable(
            name="exercise",
            table='"exercises"',
        ),
        migrations.AlterModelTable(
            name="world",
            table='"universes"',
        ),
    ]
